version: '3'
services:
    app:
        build:
            context: ./dev-image
        tty: true
        volumes:
            - .:/app
            - /app/node_modules
        ports:
            - '5173:5173'
