// Generated by Wrangler by running `wrangler types`

interface Env {
    MY_VAR: 'Hello from Cloudflare'
    REMIX_HONO_SAMPLE_SESSION: KVNamespace
    SESSION_SECRET_KEY: string
    GOOGLE_CLIENT_ID: string
    GOOGLE_CLIENT_SECRET: string
    OAUTH_CALLBACK_URL: string
}
