name = "remix-hono-sample"
compatibility_date = "2024-04-01"
compatibility_flags = [ "nodejs_compat" ]
pages_build_output_dir = "./build/client"

[vars]
MY_VAR = "Hello from Cloudflare"

[[kv_namespaces]]
binding = "REMIX_HONO_SAMPLE"
id = "your kv namespace id"

# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "my-bucket"

# [[d1_databases]]
# binding = "DB"
# database_name = "my-database"
# database_id = ""

# [ai]
# binding = "AI"
